server:
  port:  8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: cos
    password: cos
  
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp 
      
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
      use-new-id-generator-mappings: false #jpa의 넘버링 전략 따르지 않음.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.Oracle10gDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

cos:
  key: cos1234



